# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Product.destroy_all

Product.create([
  {name: "iPhone 6 Plus", image: "http://store.storeimages.cdn-apple.com/4948/as-images.apple.com/is/image/AppleInc/aos/published/images/i/ph/iphone6/plus/iphone6-plus-box-space-gray-2014_GEO_US?wid=478&hei=595&fmt=jpeg&qlt=95&op_sharpen=0&resMode=bicub&op_usm=0.5,0.5,0,0&iccEmbed=0&layer=comp&.v=1441815170180", description: "Sapphire crystal lens cover, Face detection, Smile detection, Digital zoom, Self-timer, Digital image stabilization, Back-illuminated sensor (BSI), Autofocus (Phase detection), Touch to focus, Geo tagging", price: "$299.00"},
  {name: "iPhone 6", image: "http://store.storeimages.cdn-apple.com/4948/as-images.apple.com/is/image/AppleInc/aos/published/images/i/ph/iphone6/plus/iphone6-plus-box-silver-2014_GEO_US?wid=478&hei=595&fmt=jpeg&qlt=95&op_sharpen=0&resMode=bicub&op_usm=0.5,0.5,0,0&iccEmbed=0&layer=comp&.v=1441815246278", description: "Sapphire crystal lens cover, Face detection, Smile detection, Digital zoom, Self-timer, Digital image stabilization, Back-illuminated sensor (BSI), Autofocus (Phase detection), Touch to focus, Geo tagging", price: "$199.00"},
  {name: "iPhone 6 Plus", image: "http://store.storeimages.cdn-apple.com/4948/as-images.apple.com/is/image/AppleInc/aos/published/images/i/ph/iphone6/plus/iphone6-plus-box-space-gray-2014_GEO_US?wid=478&hei=595&fmt=jpeg&qlt=95&op_sharpen=0&resMode=bicub&op_usm=0.5,0.5,0,0&iccEmbed=0&layer=comp&.v=1441815170180", description: "Sapphire crystal lens cover, Face detection, Smile detection, Digital zoom, Self-timer, Digital image stabilization, Back-illuminated sensor (BSI), Autofocus (Phase detection), Touch to focus, Geo tagging", price: "$299.00"},
  {name: "iPhone 6", image: "http://store.storeimages.cdn-apple.com/4948/as-images.apple.com/is/image/AppleInc/aos/published/images/i/ph/iphone6/plus/iphone6-plus-box-silver-2014_GEO_US?wid=478&hei=595&fmt=jpeg&qlt=95&op_sharpen=0&resMode=bicub&op_usm=0.5,0.5,0,0&iccEmbed=0&layer=comp&.v=1441815246278", description: "Sapphire crystal lens cover, Face detection, Smile detection, Digital zoom, Self-timer, Digital image stabilization, Back-illuminated sensor (BSI), Autofocus (Phase detection), Touch to focus, Geo tagging", price: "$199.00"},
  {name: "iPhone 6 Plus", image: "http://store.storeimages.cdn-apple.com/4948/as-images.apple.com/is/image/AppleInc/aos/published/images/i/ph/iphone6/plus/iphone6-plus-box-space-gray-2014_GEO_US?wid=478&hei=595&fmt=jpeg&qlt=95&op_sharpen=0&resMode=bicub&op_usm=0.5,0.5,0,0&iccEmbed=0&layer=comp&.v=1441815170180", description: "Sapphire crystal lens cover, Face detection, Smile detection, Digital zoom, Self-timer, Digital image stabilization, Back-illuminated sensor (BSI), Autofocus (Phase detection), Touch to focus, Geo tagging", price: "$299.00"},
  {name: "iPhone 6", image: "http://store.storeimages.cdn-apple.com/4948/as-images.apple.com/is/image/AppleInc/aos/published/images/i/ph/iphone6/plus/iphone6-plus-box-silver-2014_GEO_US?wid=478&hei=595&fmt=jpeg&qlt=95&op_sharpen=0&resMode=bicub&op_usm=0.5,0.5,0,0&iccEmbed=0&layer=comp&.v=1441815246278", description: "Sapphire crystal lens cover, Face detection, Smile detection, Digital zoom, Self-timer, Digital image stabilization, Back-illuminated sensor (BSI), Autofocus (Phase detection), Touch to focus, Geo tagging", price: "$199.00"},
  {name: "iPhone 6 Plus", image: "http://store.storeimages.cdn-apple.com/4948/as-images.apple.com/is/image/AppleInc/aos/published/images/i/ph/iphone6/plus/iphone6-plus-box-space-gray-2014_GEO_US?wid=478&hei=595&fmt=jpeg&qlt=95&op_sharpen=0&resMode=bicub&op_usm=0.5,0.5,0,0&iccEmbed=0&layer=comp&.v=1441815170180", description: "Sapphire crystal lens cover, Face detection, Smile detection, Digital zoom, Self-timer, Digital image stabilization, Back-illuminated sensor (BSI), Autofocus (Phase detection), Touch to focus, Geo tagging", price: "$299.00"},
  {name: "iPhone 6", image: "http://store.storeimages.cdn-apple.com/4948/as-images.apple.com/is/image/AppleInc/aos/published/images/i/ph/iphone6/plus/iphone6-plus-box-silver-2014_GEO_US?wid=478&hei=595&fmt=jpeg&qlt=95&op_sharpen=0&resMode=bicub&op_usm=0.5,0.5,0,0&iccEmbed=0&layer=comp&.v=1441815246278", description: "Sapphire crystal lens cover, Face detection, Smile detection, Digital zoom, Self-timer, Digital image stabilization, Back-illuminated sensor (BSI), Autofocus (Phase detection), Touch to focus, Geo tagging", price: "$199.00"},
  {name: "iPhone 6 Plus", image: "http://store.storeimages.cdn-apple.com/4948/as-images.apple.com/is/image/AppleInc/aos/published/images/i/ph/iphone6/plus/iphone6-plus-box-space-gray-2014_GEO_US?wid=478&hei=595&fmt=jpeg&qlt=95&op_sharpen=0&resMode=bicub&op_usm=0.5,0.5,0,0&iccEmbed=0&layer=comp&.v=1441815170180", description: "Sapphire crystal lens cover, Face detection, Smile detection, Digital zoom, Self-timer, Digital image stabilization, Back-illuminated sensor (BSI), Autofocus (Phase detection), Touch to focus, Geo tagging", price: "$299.00"},
  {name: "iPhone 6", image: "http://store.storeimages.cdn-apple.com/4948/as-images.apple.com/is/image/AppleInc/aos/published/images/i/ph/iphone6/plus/iphone6-plus-box-silver-2014_GEO_US?wid=478&hei=595&fmt=jpeg&qlt=95&op_sharpen=0&resMode=bicub&op_usm=0.5,0.5,0,0&iccEmbed=0&layer=comp&.v=1441815246278", description: "Sapphire crystal lens cover, Face detection, Smile detection, Digital zoom, Self-timer, Digital image stabilization, Back-illuminated sensor (BSI), Autofocus (Phase detection), Touch to focus, Geo tagging", price: "$199.00"},
])